# Generated by cucumber-sinatra. (2011-04-09 22:40:47 +0100)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'app.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = Sinatra::Application

class AppWorld
  include Capybara
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  AppWorld.new
end
